nameOverride: ""
fullnameOverride: ""

imagePullSecrets: []

api:
  replicaCount: 2
  image:
    repository: ghcr.io/lopatoeo/devops-2-api
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 8000
  eventsCacheTtl: "30"
  strategy:
    maxUnavailable: 0
    maxSurge: 1
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 256Mi
  probes:
    startup:
      path: /health
      failureThreshold: 30
      periodSeconds: 5
    liveness:
      path: /health
      initialDelaySeconds: 10
      periodSeconds: 10
    readiness:
      path: /db-check
      initialDelaySeconds: 5
      periodSeconds: 5
  autoscaling:
    enabled: false
    minReplicas: 2
    maxReplicas: 5
    targetCPUUtilizationPercentage: 50
  ingress:
    enabled: true
    className: traefik
    annotations: {}
    hosts:
      - host: ""
        paths:
          - path: /
            pathType: Prefix
    tls: []
  podAnnotations: {}
  podLabels: {}
  podSecurityContext: {}
  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
    runAsNonRoot: true
    runAsUser: 10001

worker:
  replicaCount: 1
  image:
    repository: ghcr.io/lopatoeo/devops-2-worker
    tag: latest
    pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 256Mi
  podAnnotations: {}
  podLabels: {}
  podSecurityContext: {}
  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
    runAsNonRoot: true
    runAsUser: 10001

postgresql:
  image:
    repository: postgres
    tag: "16"
    pullPolicy: IfNotPresent
  port: 5432
  auth:
    username: app
    database: app
    password: change-me
  secret:
    create: true
    existingSecret: ""
  persistence:
    enabled: true
    size: 5Gi
    storageClass: ""
    accessModes:
      - ReadWriteOnce
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: "1"
      memory: 1Gi

redis:
  image:
    repository: redis
    tag: 7-alpine
    pullPolicy: IfNotPresent
  port: 6379
  persistence:
    enabled: true
    size: 1Gi
    storageClass: ""
    accessModes:
      - ReadWriteOnce
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 500m
      memory: 256Mi
