apiVersion: v1
kind: Service
metadata:
  name: {{ include "devops-app.postgresqlName" . }}
  labels:
    {{- include "devops-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
spec:
  clusterIP: None
  selector:
    {{- include "devops-app.componentLabels" (dict "root" . "component" "postgresql") | nindent 4 }}
  ports:
    - name: postgresql
      port: {{ .Values.postgresql.port }}
      targetPort: postgresql
      protocol: TCP

