apiVersion: v1
kind: Service
metadata:
  name: {{ include "devops-app.redisName" . }}
  labels:
    {{- include "devops-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  clusterIP: None
  selector:
    {{- include "devops-app.componentLabels" (dict "root" . "component" "redis") | nindent 4 }}
  ports:
    - name: redis
      port: {{ .Values.redis.port }}
      targetPort: redis
      protocol: TCP

