apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "devops-app.fullname" . }}-worker
  labels:
    {{- include "devops-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker
spec:
  replicas: {{ .Values.worker.replicaCount }}
  selector:
    matchLabels:
      {{- include "devops-app.componentLabels" (dict "root" . "component" "worker") | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- if .Values.postgresql.secret.create }}
        checksum/database-secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
        {{- end }}
        {{- with .Values.worker.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "devops-app.componentLabels" (dict "root" . "component" "worker") | nindent 8 }}
        {{- with .Values.worker.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.worker.podSecurityContext | nindent 8 }}
      containers:
        - name: worker
          image: {{ printf "%s:%s" .Values.worker.image.repository .Values.worker.image.tag | quote }}
          imagePullPolicy: {{ .Values.worker.image.pullPolicy }}
          securityContext:
            {{- toYaml .Values.worker.securityContext | nindent 12 }}
          envFrom:
            - configMapRef:
                name: {{ include "devops-app.configName" . }}
            - secretRef:
                name: {{ include "devops-app.databaseSecretName" . }}
          resources:
            {{- toYaml .Values.worker.resources | nindent 12 }}

